#!/bin/bash

# Creates a copy of all Frege files in CSPM-Frontend/src/Language/CSPM/ in
# CSPM-Frontend/__DataTypeable, and adds Data and Typeable instances using
# DataDeriver to files which has been changed.
# $1: Frege command, including classpath

mkdir -p CSPM-Frontend/__DataTypeable
for f in `ls CSPM-Frontend/src/Language/CSPM/*.fr | grep -v Lexer.fr`; do
    target=CSPM-Frontend/__DataTypeable/`basename $f`
    if [ $f -nt $target ]; then
        echo $f
        cp $f $target
        echo  -e "\n-- generated by DataDeriver" >> $target
        $1 frege.dataDeriver.Main $f >> $target
        touch -r $f $target
    fi
done
